# This is a basic workflow to help you get started with Actions

name: Azure SPN test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  login:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Azure login via SPN
        uses: azure/login@v2
        with: 
         client-id: $ {{ secrets.AZURE_CLIENT_ID }}
         tenant-id: $ {{ secrets.AZURE_TENANT_ID }}
         subscription-id: $ {{ secrets.AZURE_SUBSCRIPTION_ID }}
         client-secret: $ {{ secrets.AZURE_CLIENT_SECRET }}
         uth-type: SERVICE_PRINCIPAL_SECRET

      # Runs a set of commands using the runners shell
      - name: Verify COnnection
        run: az account show
